services:
  app:
    build:
      context: .
      target: production
    container_name: vandelaytechnologies-app
    restart: unless-stopped
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    environment:
      - ENV=${ENV}
      - VIRTUAL_HOST=vandelaytechnologies.io,www.vandelaytechnologies.io
      - LETS_ENCRYPT_HOST=vandelaytechnologies.io,www.vandelaytechnologies.io
      - LETS_ENCRYPT_EMAIL=info@vandelaytechnologies.io
    logging:
      options:
        max-size: "10m"
        max-file: "3"
