services:
  app:
    build:
      context: .
      target: production
      args:
        - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}
        - NEXT_PUBLIC_HOSTNAME=${NEXT_PUBLIC_HOSTNAME}
    container_name: vandelaytechnologies-app
    restart: unless-stopped
    ports:
      - "${DOCKER_PORT}:3000"
    networks:
      - web
    env_file:
      - .env
    environment:
      - ENV=${ENV}
      - BASE_URL=${BASE_URL}
      - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}
      - NEXT_PUBLIC_HOSTNAME=${NEXT_PUBLIC_HOSTNAME}
      - DOCKER_PORT=${DOCKER_PORT}
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    logging:
      options:
        max-size: "10m"
        max-file: "3"

networks:
  web:
    name: web
    external: true
