services:
  app:
    build:
      context: .
      target: production
    container_name: vandelaytechnologies-app
    restart: unless-stopped
    ports:
      - "${DOCKER_PORT}:3000"
    networks:
      - shared_web
    env_file:
      - .env
    environment:
      - ENV=${ENV}
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    logging:
      options:
        max-size: "10m"
        max-file: "3"

networks:
  shared_web:
    name: shared_web
    external: true
